### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by Ryuuichirou** [Ryuuichirou/protospace-37176#1]
#URL
 https://protospace-37176.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@Ryuuichirou さん、ご提出いただきありがとうございます。

ユーザーの新規登録をしようとするとエラー画面が表示されてしまい、動作の確認ができませんでした。
ユーザー登録ができることをご確認いただけましたら、再度以下のprotospace完了報告フォームをご提出いただきますようお願いします。


※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **必須項目に適切な値を入力すると、ユーザーの新規登録ができるようにしましょう**
以下のエラーページに遷移してしまい新規登録ができません。
<img width="667" alt="スクリーンショット 2021-11-26 14 48 00" src="https://user-images.githubusercontent.com/62644781/143533177-87281096-36d5-4740-a9d2-90de8bdd1b86.png">


- [ ] **フォームに適切な値が入力されていない状態では、新規登録はできず、そのページに留まるようにしましょう**
新規登録ページに留まらず、エラーページに遷移してしまいます。

**※上記により、投稿機能等も確認ができておりません。**

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
@Ryuuichirou さん、ご提出いただきありがとうございます。
動作確認途中でエラーが出てしまい、リロードしても繰り返しエラー画面が表示されるようになってしまいました。

<img width="625" alt="スクリーンショット 2021-11-26 15 28 55" src="https://user-images.githubusercontent.com/59544869/143536878-bb1eeed2-80b6-43e6-bfff-aea5878ac030.png">


**※上記により、投稿機能等も確認ができておりません。**

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
@Ryuuichirou さん、ご提出いただきありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるよう実装しましょう。**
現状、「こんにちは ◯◯」と表示されているので「、」と「さん」も表示されるように修正しましょう

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できるようにしましょう。**
編集ボタンを押すと、プロトタイプ一覧ページに遷移します
※上記により、編集機能が確認できておりません。

- [x] **ログイン状態の投稿者だけが、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう。**
削除ボタンを押すと、プロトタイプ一覧ページに遷移します

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。**
ページに留まらず、エラー画面が表示されてしまいます

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
プロトタイプ一覧ページの投稿者名をクリックしてもユーザー詳細ページに遷移しません

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう。**
そのユーザーが投稿したプロトタイプが表示されていません
<img width="715" alt="スクリーンショット 2021-11-26 16 25 59" src="https://user-images.githubusercontent.com/59544869/143542837-1de0f40b-c327-4a80-b0cc-feea358566e0.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
@Ryuuichirou さん、お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるよう実装しましょう。**
「こんにちは ◯◯ 、さん」と表示されているので「、」の箇所を修正しましょう

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。**
ページに留まらず、エラー画面が表示されてしまいます

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
URLを直接入力することで、他のユーザーが投稿したものの編集ページが開けて

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
@Ryuuichirou さん、ご提出いただきありがとうございます。
動作の確認をしたところ、修正が確認できませんでした。
マージやデプロイ忘れの可能性もありますので、改めてご確認をお願いします！

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！

**Comment by Ryuuichirou** [comment]
ありがとうございました！！
